/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: '@request.auth.id != "" && owner = @request.auth.id',
      deleteRule: '@request.auth.id != "" && owner = @request.auth.id',
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          help: "",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text1579384326",
          max: 40,
          min: 0,
          name: "name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          help: "",
          hidden: false,
          id: "text1716930793",
          max: 20,
          min: 0,
          name: "color",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          help: "",
          hidden: false,
          id: "select2546616235",
          maxSelect: 1,
          name: "mode",
          presentable: false,
          required: true,
          system: false,
          type: "select",
          values: ["tally", "toggle"],
        },
        {
          help: "",
          hidden: false,
          id: "number1177347317",
          max: null,
          min: null,
          name: "position",
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          cascadeDelete: true,
          collectionId: "_pb_users_auth_",
          help: "",
          hidden: false,
          id: "relation3479234172",
          maxSelect: 1,
          minSelect: 0,
          name: "owner",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
      ],
      id: "pbc_3028234687",
      indexes: [],
      listRule: '@request.auth.id != "" && owner = @request.auth.id',
      name: "behaviors",
      system: false,
      type: "base",
      updateRule: '@request.auth.id != "" && owner = @request.auth.id',
      viewRule: '@request.auth.id != "" && owner = @request.auth.id',
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_3028234687");

    return app.delete(collection);
  },
);
